config/routes.rb
Rails.application.routes.draw do

  resources :user_memberships
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'

  resources :reports
  resources :sponsors
  resources :partners
  resources :news
  resources :documents
  resources :topics
  resources :vouchers
  resources :events_users
  resources :memberships
  resources :events
  resources :regions
  resources :references
  resources :users
  resources :degrees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/degree.rb
class Degree < ApplicationRecord
  has_many :users
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
  belongs_to :voucher
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/events_user.rb
class EventsUser < ApplicationRecord
  belongs_to :user
  belongs_to :event
  belongs_to :membership
  enum status: {pending: 0, denied: 1, approved: 2}
end

app/models/membership.rb
class Membership < ApplicationRecord
  has_many :events_users
  accepts_nested_attributes_for :events_users, :allow_destroy => true
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/partner.rb
class Partner < ApplicationRecord
end

app/models/reference.rb
class Reference < ApplicationRecord
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :event, optional: true
  belongs_to :topic, optional: true
  enum :status => {pending: 0, denied: 1, approved: 2}
end

app/models/sponsor.rb
class Sponsor < ApplicationRecord
  belongs_to :degree, optional: true
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :topic, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  belongs_to :reference, optional: true
  belongs_to :degree, optional: true
  belongs_to :region, optional: true
  has_many :user_memberships
  accepts_nested_attributes_for :user_memberships, allow_destroy: true
  has_many :reports
  accepts_nested_attributes_for :reports, allow_destroy: true
  has_many :documents
  accepts_nested_attributes_for :documents, allow_destroy: true
  has_many :events, through: :user_memberships
  has_many :memberships, through: :user_memberships
  enum :rank => {"Not in committee": 0, "First": 1, "Second": 2, "Other": 3}

end

app/models/voucher.rb
class Voucher < ApplicationRecord
  belongs_to :event
  belongs_to :membership
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :authorized
  before_action :set_membership, only: [:show, :edit, :update, :destroy]

  # GET /memberships
  # GET /memberships.json
  def index
    @memberships = Membership.all
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @membership = Membership.new
  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new(membership_params)

    respond_to do |format|
      if @membership.save
        format.html { redirect_to @membership, notice: 'Membership was successfully created.' }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1
  # PATCH/PUT /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to @membership, notice: 'Membership was successfully updated.' }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @membership.destroy
    respond_to do |format|
      format.html { redirect_to memberships_url, notice: 'Membership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = Membership.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def membership_params
      params.require(:membership).permit(:name, :reporter)
    end
end

app/helpers/degrees_helper.rb
module DegreesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/memberships/_form.html.erb
<%= form_with(model: membership, local: true) do |form| %>
  <% if membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
      <% membership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :membership_name %>
  </div>

  <div class="field">
    <%= form.label :reporter %>
    <%= form.check_box :reporter, id: :membership_reporter %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/memberships/edit.html.erb
<h1>Editing Membership</h1>

<%= render 'form', membership: @membership %>

<%= link_to 'Show', @membership %> |
<%= link_to 'Back', memberships_path %>

app/views/memberships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Memberships</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Reporter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memberships.each do |membership| %>
      <tr>
        <td><%= membership.name %></td>
        <td><%= membership.reporter %></td>
        <td><%= link_to 'Show', membership %></td>
        <td><%= link_to 'Edit', edit_membership_path(membership) %></td>
        <td><%= link_to 'Destroy', membership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Membership', new_membership_path %>

app/views/memberships/new.html.erb
<h1>New Membership</h1>

<%= render 'form', membership: @membership %>

<%= link_to 'Back', memberships_path %>

app/views/memberships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @membership.name %>
</p>

<p>
  <strong>Reporter:</strong>
  <%= @membership.reporter %>
</p>

<%= link_to 'Edit', edit_membership_path(@membership) %> |
<%= link_to 'Back', memberships_path %>