config/routes.rb
Rails.application.routes.draw do

  resources :user_memberships
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'

  resources :reports
  resources :sponsors
  resources :partners
  resources :news
  resources :documents
  resources :topics
  resources :vouchers
  resources :events_users
  resources :memberships
  resources :events
  resources :regions
  resources :references
  resources :users
  resources :degrees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/degree.rb
class Degree < ApplicationRecord
  has_many :users
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
  belongs_to :voucher
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/events_user.rb
class EventsUser < ApplicationRecord
  belongs_to :user
  belongs_to :event
  belongs_to :membership
  enum status: {pending: 0, denied: 1, approved: 2}
end

app/models/membership.rb
class Membership < ApplicationRecord
  has_many :events_users
  accepts_nested_attributes_for :events_users, :allow_destroy => true
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/partner.rb
class Partner < ApplicationRecord
end

app/models/reference.rb
class Reference < ApplicationRecord
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :event, optional: true
  belongs_to :topic, optional: true
  enum :status => {pending: 0, denied: 1, approved: 2}
end

app/models/sponsor.rb
class Sponsor < ApplicationRecord
  belongs_to :degree, optional: true
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :topic, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  belongs_to :reference, optional: true
  belongs_to :degree, optional: true
  belongs_to :region, optional: true
  has_many :user_memberships
  accepts_nested_attributes_for :user_memberships, allow_destroy: true
  has_many :reports
  accepts_nested_attributes_for :reports, allow_destroy: true
  has_many :documents
  accepts_nested_attributes_for :documents, allow_destroy: true
  has_many :events, through: :user_memberships
  has_many :memberships, through: :user_memberships
  enum :rank => {"Not in committee": 0, "First": 1, "Second": 2, "Other": 3}

end

app/models/voucher.rb
class Voucher < ApplicationRecord
  belongs_to :event
  belongs_to :membership
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authorized
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all.includes('topic')
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.includes('topic').find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def topic_params
      params.require(:topic).permit(:topic_id, :name, :description)
    end
end

app/helpers/degrees_helper.rb
module DegreesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/topics/_form.html.erb
<%= form_with(model: topic, local: true) do |form| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :topic_id %>
    <%= form.collection_select :topic_id, Topic.order(:name),:id,:name, include_blank: true %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :topic_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :topic_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Topics</h1>

<table>
  <thead>
    <tr>
      <th>Topic</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.topic ? topic.topic.name : '' %></td>
        <td><%= topic.name %></td>
        <td><%= topic.description %></td>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Topic:</strong>
  <%= @topic.topic ? @topic.topic.name : '' %>
</p>

<p>
  <strong>Name:</strong>
  <%= @topic.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @topic.description %>
</p>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>